import type { Metadata } from "next";
import { poppins } from "@/utils/font";
import Navbar from "@/components/navbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans bg-surface">
        <Navbar />
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
